<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240212060527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create tables: author, book, author_book';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE author
            (
                id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                first_name  VARCHAR(255)                         NOT NULL,
                last_name   VARCHAR(255)                         NOT NULL,
                middle_name VARCHAR(255) DEFAULT NULL,
                PRIMARY KEY (id)
            )'
        );
        $this->addSql('CREATE TABLE author_book
            (
                author_id INT NOT NULL,
                book_id   INT NOT NULL,
                PRIMARY KEY (author_id, book_id)
            )'
        );
        $this->addSql('CREATE INDEX IDX_2F0A2BEEF675F31B ON author_book (author_id)');
        $this->addSql('CREATE INDEX IDX_2F0A2BEE16A2B381 ON author_book (book_id)');
        $this->addSql('CREATE TABLE book
            (
                id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title            VARCHAR(255)                         NOT NULL,
                image            VARCHAR(255) DEFAULT NULL,
                description      TEXT         DEFAULT NULL,
                publication_date DATE         DEFAULT NULL,
                PRIMARY KEY (id)
            )'
        );
        $this->addSql('ALTER TABLE author_book 
            ADD CONSTRAINT FK_2F0A2BEEF675F31B 
                FOREIGN KEY (author_id) 
                    REFERENCES author (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE author_book
            ADD CONSTRAINT FK_2F0A2BEE16A2B381 
                FOREIGN KEY (book_id) 
                    REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE author_book DROP CONSTRAINT FK_2F0A2BEEF675F31B');
        $this->addSql('ALTER TABLE author_book DROP CONSTRAINT FK_2F0A2BEE16A2B381');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE author_book');
        $this->addSql('DROP TABLE book');
    }
}
